services:
  - type: web
    name: Email_Automation_Tool
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    postDeployCommand:
      - flask db upgrade