services:
  - type: web
    name: Email_Automation_Tool
    env: python
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "flask db upgrade"
    startCommand: "gunicorn app:app"